/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	//Enable RCC Clock for pheripheral memory
	//Use volatile for memory mapped IO(Volatile data) GPIOA
	uint32_t volatile *pclkperipheralenablereg = (uint32_t*) 0x40023830;
	// gpioA mode register as Input (GPIOA)
	uint32_t volatile *pgpioamodereg = (uint32_t*) 0x40020000;
	//Enable Gpio led pin(PD12)
	uint32_t volatile *pgpiodledpin = (uint32_t*) 0x40020014;
	uint32_t volatile *pgpioadatareg = (uint32_t*) 0x40020010;

	//Enable gpioa
	*pclkperipheralenablereg |= (1 << 0);
	//SET gpioa 0th pin as input and 5 bit as output in mode register
	*pgpioamodereg |= (1 << 10);

	while (1)

	{
		uint8_t val = (uint8_t) (*pgpioadatareg & 0x1);
		if (val) {
			*pgpiodledpin |= (1 << 5);
			printf("LED is ON\n");
		} else {
			*pgpiodledpin &= ~(1 << 5);
			printf("LED is OFF\n");
		}
	}
}
