/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include<stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
    //data is unsigned
	printf("size of int in Nucleo board %d\n", sizeof(int));
	printf("size of short in Nucleo board %d\n", sizeof(short));
	printf("size of long in Nucleo board %d\n", sizeof(long));
	printf("size of char in Nucleo board %d\n", sizeof(char));
	printf("size of long long in Nucleo board %d\n", sizeof(long long));
	printf("size of float in Nucleo board %d", sizeof(float));
	printf("size of double in Nucleo board %d", sizeof(double));
}
