/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	//InBuild LED PA5 Flash Program
	//Enable RCC Clock for pheripheral memory
	uint32_t *pclkperipheralenablereg = (uint32_t*) 0x40023830;
	// gpio PORT mode register as output (GPIOD)
	uint32_t *pgpioaportmoderegister = 0x40020000;
	//Enable Gpio led pin(PA5)
	uint32_t *pgpioadatareg = 0x40020014;

	//SET GPIOA pin 0 of RCC AHB1 peripheral clock enable register (RCC_AHB1ENR)
	*pclkperipheralenablereg |= (1 << 0);
	//GPIO port mode register (GPIOx_MODER) (x = A..E and H), set PA5 as output(11 and 10 pin as 0,1)
	*pgpioaportmoderegister |= (1 << 10);
	//GPIO port output data register (GPIOx_ODR) (x = A..E and H) , set PA5 as high
	*pgpioadatareg |= (1 << 5);
	//LED ON for ever
	while (1)
		;

}
